version: '3'

x-common-variables: &common-variables
    POSTGRES_DB: db_kiddymap
    POSTGRES_USER: usr_kiddymap
    POSTGRES_PASSWORD: kiddymap

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kiddymap-network

  kiddymap-db:
    image: postgres:14
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: "always"
    volumes:
      - "./docker/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment: *common-variables
    networks:
      - kiddymap-network

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    expose:
      - "9001"
    networks:
      - kiddymap-network
    healthcheck:
      test: curl http://config-server:9001

  eureka-server:
    depends_on:
      config-server:
        condition: service_healthy
    image: eureka-server
    container_name: eureka-server
    build:
        context: ./eureka-server
        dockerfile: Dockerfile
    ports:
        - "8761:8761"
    expose:
        - "8761"
    restart: "always"
    networks:
      - kiddymap-network

  api-gateway:
    depends_on:
      - config-server
      - eureka-server
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
        - "9004:9004"
    expose:
        - "9004"
    restart: "always"
    networks:
      - kiddymap-network

  microservice-profil:
    depends_on:
      - config-server
      - eureka-server
      - kiddymap-db
    image: microservice-profil
    container_name: microservice-profil
    build:
      context: ./microservice-profil
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    expose:
      - "9002"
    restart: "always"
    networks:
      - kiddymap-network

  microservice-location:
    depends_on:
      - config-server
      - eureka-server
      - kiddymap-db
    image: microservice-location
    container_name: microservice-location
    build:
      context: ./microservice-location
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    expose:
      - "9003"
    restart: "always"
    networks:
      - kiddymap-network

networks:
  kiddymap-network:
    driver: bridge